#!/bin/sh

# _                                          
# | |                                         
# | |__  ___ _ ____      ___ __ ___  _ __ ___ 
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
# | |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#           | |                               
#           |_|                                  


# ################################################################################
# # #                                AUTOSTART APPS                              #
# # ##############################################################################

#start sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

#start polybar
$HOME/.config/polybar/launch.sh &

#start picom
picom --experimental-backend &

#start conky
conky --config=$HOME/.config/conky/conky.conf &

# ################################################################################
# # #                                  Wallpaper                                 #
# # ##############################################################################

#set wallpaper with 'feh'
feh --no-fehbg --bg-fill /home/muk/Pictures/wallpaper/093.jpg &


# ################################################################################
# # #                                  Window Rules                              #
# # ##############################################################################

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off


# ################################################################################
# # #                                  Generell Settings                         #
# # ##############################################################################

bspc monitor VGA-1 -d 1 2
bspc monitor VGA-2 -d 3 4

bspc config border_width         2
bspc config window_gap		 12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Fix cursor
xsetroot -cursor_name left_ptr

# Fix Java applications
export _JAVA_AWT_WM_NONREPARENTING=1

################################################################################
#                                    Appearance                                #
################################################################################
#Color in the borders when the app is active
bspc config focused_border_color "#c50ed2"
bspc config normal_border_color "#292f45"
bspc config presel_feedback_color "#c50ed2"
